### ISSUE TITLE
Consider moving "troubleshooting" methods to another interface

### ISSUE THREAD

**Issue by tomas-langer** [jakartaee/config#13]
Currently `Config` contains methods to access meta configuration ("ConfigConfig"), such as `getConfigSources()`

These methods may be confusing for end user, as they should not be used (except for troubleshooting purposes, or for some advanced use cases - @struberg, could you please share such a use case here?).

These may be moved to a separate class (and should be moved if we go with tree structure).

**Comment by radcortez** [comment]
We removed the MP APIs copied on the initial commit, so this no longer applies.
