### ISSUE TITLE
ConfigProviderResolver vs. ConfigProvider

### ISSUE THREAD

**Issue by tomas-langer** [jakartaee/config#14]
According to javadoc and location the `ConfigProviderResolver` class is intended for implementors of Jakarta Config, as the main entry point. `ConfigProvider` is then the main entry point for a user.
`ConfigProvider` only allows user to get hold of a `Config` instance, but does not have any support for more advanced use cases (such as registration of config, creating a new config using a builder).

It may be useful to create `static` methods on `ConfigProvider`, so end user never needs to use `ConfigProviderResolver` class.

e.g.: 
`ConfigProvider.newBuilder()`
`ConfigProvider.register(Config config)`

**Comment by radcortez** [comment]
`ConfigProvider` and `ConfigProviderResolver` were removed. Closing this.
