### ISSUE TITLE
Potential naming clash with java.rmi.NoSuchObjectException

### ISSUE THREAD

**Issue by tevans78** [jakartaee/config#163]
To avoid IDEs automatically importing the wrong class, it might be a good idea to rename [jakarta.config.NoSuchObjectException](https://github.com/jakartaee/config/blob/main/api/src/main/java/jakarta/config/NoSuchObjectException.java) to something else. There is a class of the same name in the JDK [java.rmi.NoSuchObjectException](https://docs.oracle.com/en/java/javase/17/docs/api/java.rmi/java/rmi/NoSuchObjectException.html)

**Comment by radcortez** [comment]
`jakarta.config.NoSuchObjectException` was removed.
