### ISSUE TITLE
TypeToken.mostSpecializedParameterizedSuperclass(Type type) should not return null

### ISSUE THREAD

**Issue by tevans78** [jakartaee/config#164]
If, for some strange reason, you do this...
```
TypeToken<?> t = new TypeToken() {};
```
then you get
```
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.ParameterizedType.getActualTypeArguments()" because the return value of "typetoken.TypeToken.mostSpecializedParameterizedSuperclass(java.lang.reflect.Type)" is null
```

Given that [mostSpecializedParameterizedSuperclass](https://github.com/jakartaee/config/blob/3f32d61696a9d173fd8d26ce1f4a861731e8281d/api/src/main/java/jakarta/config/TypeToken.java#L388) is a private method which is only ever called from the [constructor](https://github.com/jakartaee/config/blob/3f32d61696a9d173fd8d26ce1f4a861731e8281d/api/src/main/java/jakarta/config/TypeToken.java#L73) of TypeToken, it isn't a good idea for it to ever return null. If it does ever return null (through misuse of TypeToken), the result will be a generic NPE rather than an specific exception with a helpful error message.

Suggest throwing some flavour of ConfigException rather than returning null. The exception message can be specific to the if block which is throwing it.

Alternatively, if mostSpecializedParameterizedSuperclass can return null, put a null check in the TypeToken constructor and throw the ConfigException from there. However, at this point you will have lost some context about what the (very unexpected) problem is.

Credit to @Azquelt for spotting this issue.

**Comment by jansupol** [comment]
@tevans78 Thank you for spotting this. Feel free to provide a PR :)

**Comment by radcortez** [comment]
TypeToken was removed.
