### ISSUE TITLE
Add ConfigruationProperties to group config properties

### ISSUE THREAD

**Issue by hantsy** [jakartaee/config#19]
Provides a Spring `@ConfigurationProperties` or MP `@ConfigProperties`/`@ConfigMapping` like annotation on  `interface`, `record` and `POJO` classes, etc. to group config properties.

```java

@ConfigurationProperties(prefix="server")
public record ServerConfig(
    @ConfigProperty(name="protocol", defaultValue="http") //named to "protocol" and set default value to "http"
    String schema, 
    String host,
    int port
){}
```

**Comment by joakime** [comment]
How would this be used?

**Comment by hantsy** [comment]
> 
> 
> How would this be used?

Configure the properties by properties file, system env or system variables, and use it a CDI bean by inject type safe  `ServerConfig`.

```java
@ApplicationScoped
class SomeBean{
    @Inject ServerConfig serverConfig;
}
```

**Comment by radcortez** [comment]
`@ConfigMapping` is currently part of the API.
