### ISSUE TITLE
load(Class) method expects annotated interface

### ISSUE THREAD

**Issue by jansupol** [jakartaee/config#212]
During the meeting, it was discussed the `Loader.load(Class<?>)` expects an interface class that is annotated by `@Configuration` interface.

This annotation does not seem to be required any longer when `path` method replaces the `@Configuration.path`.

**Comment by radcortez** [comment]
The `@ConfigMapping` is mandatory when calling `load(Class<?>)`. For other cases that may require retrieving configuration without an interface (for instance, Jakarta specifications), there will be a programmatic API for that use case.
