### ISSUE TITLE
Support EL in Config value

### ISSUE THREAD

**Issue by hantsy** [jakartaee/config#248]
For example, in a config properties file, we could use EL as partial value of config property.

```properties
a.name=hello
b.name=#{a.name} world // or ${a.name} world

```

**Comment by radcortez** [comment]
Yes. I think we all agreed that we want to support some expression replacement mechanism.

I don't know if it should be EL or something else. Probably, EL has a lot of things that do not make sense in this context, so we need to have a proper discussion around it.

**Comment by radcortez** [comment]
Duplicate of #77
