### ISSUE TITLE
Ability to work with a list of configured values of single values

### ISSUE THREAD

**Issue by Emily-Jiang** [jakartaee/config#36]
As an app devleoper, I want to read a list or array of configured values of single values. An example would be a list of valid keys, or a list of specially handled business keys.

**Comment by Emily-Jiang** [comment]
list.1=
list.2
list=apple, orange

**Comment by tomas-langer** [comment]
Two sides to this story:
1. configuration files (probably depends also on file type - yaml, properties)
2. API to retrieve this value (probably a single way to read an array/list)

**Comment by hantsy** [comment]
>     2. API to retrieve this value (probably a single way to read an array/list)

Add a built-in converter for this.

**Comment by hantsy** [comment]
Consider adding built-in converters for  `Collection`, `Map`, and array type as key.

```properties
config.alist=apple,orange
config.amap=a,apple,o,orange
config.array=apple,orange
```

**Comment by radcortez** [comment]
For the `properties` format, my recommendation to represent Collections and Maps is the following:

```properties
# Collections
config.list[0]=foo
config.list[1]=bar

#Maps (the Map key is the last segment of the property)
config.map.key=foo
config.map.anotherKey=bar
```

This avoids issues with escaping the comma used to split the values, and in my opinion, it is also more explicit and clear. It has some more pros for advanced stuff. For instance, complex types:

```properties
server.host=localhost
server.port=8080
server.endpoints[0].path=/hello
server.endpoints[0].method=GET
```

**Comment by radcortez** [comment]
`@ConfigMapping` will provide support for this.
